### PR TITLE
[AHKv2]Fix Findelements, add session.Title

### PR DESCRIPTION
**Pull request by enaaab460**
I think I fixed findelements method in Elements.ahk
I think part of the problem was that the outer loop was using Element as map value, and the innermost loop was using walling Element class, so I changed the map to Elements.
Then I used insertat to push to the e array, since the original way caused errors.

### CODE REVIEW

**Comment by enaaab460** [comment]
PS: first time using Pull request.
Don't know how to use properly or should I even use it.

**Comment by Xeo786** [comment]
your changes are from Session.ahk 
findElements() is work and expected but there is no Session.Title will add shortly

**Comment by enaaab460** [comment]
> your changes are from Session.ahk findElements() is work and expected but there is no Session.Title will add shortly

My bad, I meant sessions.ahk. When I used session.querySelectorAll of the sessions.ahk file,  I got the error: "Map has no method named Call" in calls tack of findelements method of sessions.ahk.

After my modification it worked as expected

**Comment by enaaab460** [comment]
Just tried now. The original elements.ahk had the same error when using element.querySelectorAll().
When I made the same modifications as sessions.ahk it worked.
I replied these modifications to issue #30 as we both have the same problem

**Comment by Xeo786** [comment]
now I noticed element from for loop  and class element conflict but I much use count because length if array starts from 0, `array.InsertAt(0,"somevar")` then the length will still remain 0 but count will give you array count 1 so I made the change as you suggested

**Comment by enaaab460** [comment]
> now I noticed element from for loop and class element conflict but I much use count because length if array starts from 0, `array.InsertAt(0,"somevar")` then the length will still remain 0 but count will give you array count 1 so I made the change as you suggested

I tried using `if e.count() > 0` again and got Error: Missing a required parameter.
I don't think arrays have count method (atleast in ahk v2)

**Comment by enaaab460** [comment]
Just discovered that index 0 doesn't work with insertat. the first element is index 1

**Comment by enaaab460** [comment]
but e[k-1] := element(....) caused error as well

**Comment by Xeo786** [comment]
ops I am still confused with v1 and v2 count is not method its property I just fixed, but I can't test it right now please confirm if it works

**Comment by enaaab460** [comment]
Length works, but I can't get index 0 to work with original way or insertat way

**Comment by enaaab460** [comment]
e.count ;without brackets caused this error `Error: Expected a Number but got a Func.`

**Comment by enaaab460** [comment]
E.length works fine

**Comment by enaaab460** [comment]
arrays don't have count method or property in AHK2

**Comment by enaaab460** [comment]
count is for maps

**Comment by Xeo786** [comment]
I just check documents they fixed length in V2 
` 
; v1 code 
e := []
e.Insertat(0, "somewar")
msgbox % e.Length() ; this will return 0 v1
`
let me fixed too I will soon working on Rufaydium V2 a separate library soon 
Thanks you enaab and sorry I didn't understand what you were facing

**Comment by enaaab460** [comment]
index 0 works if e is map()

**Comment by enaaab460** [comment]
But using for loop now needs 2 variables for enumeration as the following example, so it may break any script looping with 1 variable only (which is what I did)
I updated the example i made in issue #30 
```
browser := Rufaydium("Down\webdrivers\chromedriver.exe")
browser.capabilities.setUserProfile("Profile 1")
document := browser.NewSession()
document.url := "facebook.com"
output:=""
for ind,elem in document.querySelector('.x78zum5.xdt5ytf.x1iyjqo2.x1us19tq').querySelectorAll('a'){
    output.=elem.innerText "`n"
}
msgbox output
MsgBox document.querySelector('.x78zum5.xdt5ytf.x1iyjqo2.x1us19tq').querySelectorAll('a')[1].innerText ; gets the second element
```

**Comment by enaaab460** [comment]
If you choose to change it to a map,  I think you should make an alert/notification as maps don't work exactly as arrays, so some scripts might need modification.
And since the index can now be 0, all index will be shifted by 1

**Comment by Xeo786** [comment]
yes I have just check 
```
e := Map()
e[0] :=  "somewar"
for k, v in e
        msgbox k "`n" v
```
following code works

**Comment by Xeo786** [comment]
I remeber I was having issues with map() i do not remeber this is why I swicthed to array() and I also rememebr now that array being started from 1 not zero

for now I just used Map() which does not support .length as prop so return to count 

please check if you face any issue. or may be we need to switch to array and index will start from 1 unlike JS

**Comment by Xeo786** [comment]
yeah I have updated that and test following code

```

**Pull request closed without merging**
