### PR TITLE
Toggle to show webdriver

### PR DESCRIPTION
**Pull request by hi5**
To debug it would be nice to have a visible webdriver, so added a Visible parameter and added it to launch() - perhaps not he most elegant method.

if you run `Driver := new RunDriver(ChromeDriver,,,1)` webdriver should be visible.

### CODE REVIEW

**Comment by hi5** [comment]
This more to illustrate, so feel free to implement something yourself if you think it is a good idea and close the pull request. (side note: do a trim trailing spaces in your editor for all files)

**Comment by Xeo786** [comment]
How about driver.show() driver.hide() when ever needed. I think I can do it

**Comment by Xeo786** [comment]
You requirement has been implemented https://github.com/Xeo786/Rufaydium-Webdriver/blob/main/WDM.ahk#L53
see example https://github.com/Xeo786/Rufaydium-Webdriver#rundriver

**Comment by hi5** [comment]
Elegant solution

**Pull request closed without merging**
